Itaka scrapping
WariatInc/scrappers pull request #2
Opened 2023-03-23 09:58 UTC by JakubKoniuszewski

2023-03-24 13:19 UTC, MD-00 commented on .gitignore
dodajcie tu .idea i wywalcie z głównego folderu .idea

2023-03-24 14:03 UTC, xTaube commented on .gitignore
+1

2023-03-24 14:06 UTC, xTaube commented on scrappers/itaka/scraper.py
> +        self.offer_urls: List[str] = self.get_itaka_urls()
od wersji pythona 3.9 do typing można używać standartowej listy https://peps.python.org/pep-0585/
przykładowo `list[str]`. `List` z typingu jest deprecated

2023-03-24 14:12 UTC, xTaube commented on scrappers/itaka/scraper.py
> +        self.save_json_as_file(filename="itaka_offers")
nie wywoływałbym tego w konstruktorze, każde stworzenie instancji spowoduje utworzenie pliku a nie zawsze może być to pożądane

2023-03-24 14:18 UTC, xTaube commented on scrappers/itaka/scraper.py
> +        return offer_urls
niepotrzeba zmienna `offer_urls`
```suggestion
        return [
            f"https://www.itaka.pl{title.find('a')['href']}" 
            for title in offer_titles
        ]

```

2023-03-24 14:23 UTC, xTaube commented on scrappers/itaka/scraper.py
> +            ) = self._room_picker(html_content)
możesz to zwrócić od razu jako dict opisujący pokój

2023-03-24 14:27 UTC, xTaube commented on scrappers/itaka/scraper.py
> +scraper = ItakaScraper(WEBSITE_URL, NO_OF_SCRAPED_OFFERS)
Dobrym nawykiem przy skryptach jest stosowanie takiej konwencji
```suggestion
def main(*comand_line_args: str) -> None:
    scraper = ItakaScraper(WEBSITE_URL, NO_OF_SCRAPED_OFFERS)
    scrapper.save_json_as_file("itaka_offers")
       
if __name__ == "__main__":
    main()
```

2023-03-24 14:28 UTC, xTaube requested changes
Ogólnie LGTM, tylko drobne poprawki

2023-03-25 09:43 UTC, Mazurel commented on scrappers/itaka/.itaka_offers.json.swp
Ten plik raczej powinien być dodany do `.gitignore`

2023-03-25 09:44 UTC, Mazurel commented on requirements.txt
Ja bym sugerował: `scrappers/itaka/requirements.txt` - Każdy scraper raczej będzie miał inne paczki.

2023-04-13 16:59 UTC, LukaszSzarecki approved these changes

2023-04-13 16:59 UTC, merged